### ISSUE TITLE
Invalid JSON Patch when trying to Merge

### ISSUE THREAD

**Issue by w0rm3r** [Velocidex/velociraptor#1330] opened 2021-10-14 17:04 UTC
Velociraptor keeps failing to Merge JSON file. For example: `velociraptor.exe config generate --merge deploy.json > server.config.yaml`

This command when passed by a _PowerShell Script_ (Ps1) will run and _"server.config.xml"_ will be created. But instead of _deploy.json_ file being part of the _server.config.yaml_ it only states "Invalid merge patch: Invalid JSON Patch"

The JSON in question is a modified template by @mgreen27, something he shared on Discord awhile back.

Example of deploy.json
```
"Frontend": {
        "hostname": "localhost",
        "bind_address": "127.0.0.1",
        "bind_port": 8000,
        "public_path": "/opt/velociraptor/velociraptor",
        "default_client_monitoring_artifacts": [
            "Generic.Client.Stats"
        ],
        "dyn_dns": {
            "ddns_username": "",
            "ddns_password": ""
        }
    },
```

This Invalid JSON Patch occurs when the script runs the command, or when the command is manually inputed by user. Tested on Windows 10, Windows Server 2016, 2019, 2022.

**Comment by 0e29** [comment] 2021-10-16 08:22
I'm aware of { } for JSON. It simply was not included in my example snippet. Now not entirely sure if this is an issue relating to Windows system as I have not deployed Velociraptor on Linux. But the --merge won't work even if just raw JSON is supplied.

`config generate --merge '{"bind_address":"127.0.0.1"}' > config.yaml`

A config.yaml is created by PowerShell Process. But it's same output as my initial issue. "Invalid merge patch: Invalid JSON Patch".

I honestly understand if I was doing something like `$json = Get-Content payload.json -Raw` and then calling `"$json`" in the -ArgumentList. But no matter how I try to merge it will either display no output, or  "Invalid merge patch: Invalid JSON Patch". is written to the output file.

Removing `> config.yaml` will yield no results as configs aren't created but it most likely fails. PowerShell is not complaining about JSON so I know it's being passed correctly via -ArgumentList.

**Comment by scudette** [comment] 2021-10-16 09:11
You example above has an incorrect json object - it should be
```
config generate --merge '{"Frontend": {"bind_address":"127.0.0.1"}}' > config.yaml
```

The thing you are merging with has to be a valid configuration json file and follow the proper schema.

**Comment by scudette** [comment] 2021-12-24 00:09
Closing as this is working as intended - please reopen if it is still not working for you

**Closed by scudette** 2021-12-24 00:09 UTC
