### ISSUE TITLE
Version 0.6.5-2 wont generate RHEL Multi-Frontend RPMs

### ISSUE THREAD

**Issue by Marlin290272** [Velocidex/velociraptor#1974] opened 2022-08-06 21:57 UTC
Version 0.6.5-2 wont generate RHEL Multi-Frontend RPMs. I was able to it to generate the debian packages for Ubuntu but not RHEL

**Comment by scudette** [comment] 2022-08-06 21:59
Duplicate of #1967

**Closed by scudette** 2022-08-06 21:59 UTC
