### ISSUE TITLE
Nginx reverse proxy setup - font problem 

### ISSUE THREAD

**Issue by m4r2** [Velocidex/velociraptor#3861] opened 2024-10-29 12:20 UTC
I deployed the Velociraptor server behind a Nginx reverse proxy and I have the problem, that the fonts can't be loaded.
I have used the Nginx configuration as described in that article: https://docs.velociraptor.app/blog/2020/2020-09-28-velociraptor-network-communications-30568624043a/

In the console of the browser I've found these errors, that iosevka-term-medium-subset-d289edc8.woff2 can't be loaded:
![image](https://github.com/user-attachments/assets/5a2b9ebf-fff4-40b2-92d9-ccda9bec3d24)
As you can see in the screenshot, the domain is missing in the link. This causes the GUI to become slow and a standard font is used.
![image](https://github.com/user-attachments/assets/0d202223-4d23-4b91-846e-bf60e161e5c7)
An other problem (maybe related) is, when I request https://<domain>/gui, the gui loads but it redirects the browser to https://<domain>/app. When I do reload I get an error 404, because the reverse proxy config does not include /app.

I use Velociraptor 0.73.2.

**Comment by scudette** [comment] 2024-10-29 13:08
This is probably related to, or a duplicate of #3859 . I think the loading of the fonts is not actually easy to solve - we have seen it before here https://discord.com/channels/624244632552734750/624244632552734752/1270545691260883059

**Closed** 2024-10-30 08:55 UTC
