### ISSUE TITLE
Exporting Results in 6.7 

### ISSUE THREAD

**Issue by obvivdo** [Velocidex/velociraptor#2402] opened 2023-01-30 01:20 UTC
Exporting all results and result summaries for hunts which contain artifacts with multiple artifact sources will generate a ZIP with indentical JSON / CSV file paths for each source. Upon unziping the results, only one source result file will be present as the others will have been overriden during extraction. This was tested using the `Generic.Client.Info` artifact on VR versions `6.6` and `6.7` on Windows and Linux installs. Version `6.6` correctly exports results with distinct filenames per source, whilst `6.7` does not.

Attached Image has version 6.6 on top and version 6.7 on bottom 

![vr-export-6 6vs6 7](https://user-images.githubusercontent.com/63890095/215368597-727d327f-03a2-4fad-b842-0760ba0acde4.png)

**Comment by scudette** [comment] 2023-01-30 01:30
This is a duplicate of #2336 should be fixed in 0.6.8

**Closed by scudette** 2023-01-30 01:30 UTC
