### ISSUE TITLE
Trouble with repeat clients, try to workaround but does not work

### ISSUE THREAD

**Issue by ezpz4n6** [Velocidex/velociraptor#2731] opened 2023-06-05 02:35 UTC
Velociraptor version:  
- Server: v0.6.8-2
- Clients: v0.6.8

# Issue:
I have deployed velociraptor to a bunch of clients. But, some of them have been repeated

![image](https://github.com/Velocidex/velociraptor/assets/48788455/892dc52e-de4a-4eeb-bbce-51a4197d2c38)

In this picture above, the client has same hostname, same fqdn, same IP, .. but multiple ClientId. 

I used ` Server.Telegram.Clients.Enrolled` artifact to recive message when a new connection from client. As you can see, client connect to server from same ip (different port) each time

![image](https://github.com/Velocidex/velociraptor/assets/48788455/67845749-eba8-45bd-b248-ac82273f9352)

I think it could be a problem with `writeback` file, so i get info about it. MTime and CTime have been changed, seem like it could be read, write as well.

![image](https://github.com/Velocidex/velociraptor/assets/48788455/92b96bbd-faab-423c-8229-4cb4a6d3fc38)

# PS:
I have been reinstall client, remove everything in Velociraptor folder, still get this issue

Please check and help me figure out, thanks!

**Comment by ezpz4n6** [comment] 2023-06-05 02:37
@scudette i am very glad full if you check it out

**Comment by scudette** [comment] 2023-06-05 02:42
If the client id is being changed then the writeback is being regenerated ( the client id is in the writeback file). We need to see why the writeback is being regenerated all the time. How is the MSI being deployed? Is it possible that MSI is reinstalled more than once - this should not change the client id i dont think, because MSI should not reinstall if it is already installed, but maybe it is uninstalled completely then reinstalled?

**Comment by ezpz4n6** [comment] 2023-06-05 03:11
I have been deploy MSI via GPO. I can confirm that my client does not anything with velociraptor service

**Comment by scudette** [comment] 2023-06-05 03:42
You can verify if the file is being overwritten by just getting the file with eg the vfs at two times and see if the client id and public key are changed between each capture

**Comment by scudette** [comment] 2023-09-30 00:36
This seems to be a duplicate of #2955 or somehow related

**Closed** 2023-10-08 13:27 UTC
