### ISSUE TITLE
Support for Cross-OS Analysis

### ISSUE THREAD

**Issue by lucebac** [Velocidex/velociraptor#1425] opened 2021-12-10 16:14 UTC
We from time to time come across situations where we would like to collect forensic artifacts on a Windows disk image while operating from a Linux OS. Currently, Velociraptor seems to not support these kind of setups. We could manage to tweak some file-based artifacts to work under the given circumstances but we cannot unlock the full set of features of Velociraptor, especially for Windows targets.

Given that most of the code only conditionally compiles for a given GOOS target but otherwise has a surprisingly low amount of dependencies on OS-specific code, we asked ourselves whether it would possible to introduce a cross-platform or cross-OS analysis feature to Velociraptor. The idea we ended up with is roughly as follows:

Say, we would run Velociraptor like this: `./velociraptor client --analysis-target windows --device /path/to/disk/image <more args>`. What the result then could be is that Velociraptor internally (only) enables and uses all available Windows features despite running on, e.g., a Linux host. Additionally, the supplied disk image should be used as the analysis target instead of the filesystem of the host.

I would kindly like to ask whether whether or not you see this as a fit for the project. If so, I would additionally like to know whether you generally consider this possible to implement or if you see major obstacles with the current implementation.

**Comment by scudette** [comment] 2021-12-10 16:23
Yes this is basically a duplicate of #888 

Generally there are two kinds of plugins - os dependant ones use the APIs like pslist etc and parsers which just parse files, like prefetch, raw reg, ntfs etc

The api plugins can not work on dead disk analysis but the parsers certainly can.

The some artifacts mix both - for example, do a glob then use authenticode to verify the binaries (that one is half parser and half os api to verify the sigs). One of the dangers is that the artifact might get confused and combine dead disk data with api data (from the analysis machine itself). Additionally we dont want to make people change the artifacts manually - the same artifact needs to work the same on live systems and on dead systems.

so to make it work we need a way to disable API access completely (so it just fails) and still allow parser access so artifacts that try to combine two types of data just end up with blank for the api derived data.

The way you are proposing is pretty much the way I was thinking it would work. Have some flags that initialize the client in a way that makes it look like a drive is mapped to say a directory or image. So the flags preconfigure it in a certain mode of operation.

**Comment by scudette** [comment] 2022-03-28 00:58
Done will be out in 0.6.4

**Closed by scudette** 2022-03-28 00:58 UTC
