### ISSUE TITLE
Delete client behaviour not quite as expected

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#947] opened 2021-03-02 18:21 UTC
Deleting clients in the GUI invokes the `Server.Utils.DeleteClient` artifact which purges the client's data from the filestore. That part works, however the client still continues communicating behind the scenes and doesn't re-enrol because it still has valid credentials. Restarting the client does not change the situation because it has it's writeback.yaml and is unaware of the server-side change. If the writeback file is deleted and the client is restarted then it re-enrols.

The DeleteClient artifact states:

> if the client still exists, it will just  automatically re-enrol when it next connects. You will still be able  to talk to it, it is just that old collected data is deleted.

On the server the deleted client cannot be accessed or instructed to do anything. It does not participate in hunts.

I actually like the current behaviour because when I delete a client I don't want to see it again, or have it participate in hunts, even if it is out there. Manual intervention (i.e. deleting the writeback), is a nice control step that can be taken if one reeeeally wants the client to come back. So perhaps it's just that the artifact / GUI needs to be updated to match the current behaviour?

**Comment by scudette** [comment] 2021-03-03 01:29
The issue is that the client's key is cached in memory so even when the key is removed from the data store it is still in the key cache and therefore we are able to talk with it freely so the client does not enroll because it thinks all is well with it.
If you restart the server than the key cache will be rebuilt and the client will re-enrol

**Comment by predictiple** [comment] 2021-03-03 15:19
I don't believe so. After deleting a client you can restart the client and/or the server as many times as you want, and the client does not re-enroll. Deleting the client's writeback file and restarting it allows the re-enroll to happen.

**Comment by scudette** [comment] 2021-03-03 23:02
Deleting the client write back file will cause it to regenerate a new id so that's why it re enrols.

**Comment by predictiple** [comment] 2021-03-04 06:50
As I've said, I think the current behaviour is fine and I don't want it to change. It's just that the artifact description (being the only form of documentation regarding the GUI delete action that I could find) says that active clients will re-enroll, while my testing suggests that they don't, and that might be contrary to expectations.

I'm happy to close this issue if you agree? If it comes up again for anyone else then we can revisit it.

**Comment by scudette** [comment] 2021-03-04 06:55
Not at all! this is a valid issue - thanks for opening it. The client should re-enroll if it is still out there. We need to fix it by having the ability to remove the client's key from the key cache here

https://github.com/Velocidex/velociraptor/blob/51eda4f0254387b2255302098a9752ef4150e24e/vql/server/delete.go#L88

**Comment by predictiple** [comment] 2021-03-04 07:01
If this issue is fixed then we are going to need a "Delete and Block" button too :smiley_cat:

**Comment by scudette** [comment] 2021-04-29 01:46
This should be fixed in 0.5.9 - deleting a client that is still active will re-enrol it within a few minutes

**Closed by scudette** 2021-04-29 01:46 UTC
