### ISSUE TITLE
Feature request: Elastic.Flows.Upload to cover the offline collected import

### ISSUE THREAD

**Issue by Walishaha** [Velocidex/velociraptor#2908] opened 2023-08-24 06:54 UTC
Hi VR team,

Recently I was trying to ship the collected artifacts JSON data to Elastic using "Elastic.Flows.Upload" and it worked pretty well for artifacts collected after the configuration of  "Elastic.Flows.Upload". 

I also had some offline collected artifacts that I imported to the VR server using "Server.Utils.ImportCollection"  and wanted to ship to Elastic but seems the  "Elastic.Flows.Upload" is not covering those imported offline collections.

Can you please add a server event artifact to VR that could ship the offline imported collection using "Server.Utils.ImportCollection"

Thank you

**Comment by scudette** [comment] 2023-08-26 11:26
Duplicate of #2798

**Closed by scudette** 2023-08-26 11:26 UTC
